# Generated by Django 2.1.7 on 2019-03-06 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '大图',
                'verbose_name_plural': '大图',
                'ordering': ('image_id',),
            },
        ),
        migrations.CreateModel(
            name='BigPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_path', models.CharField(max_length=100)),
                ('pic_path1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_price', models.SmallIntegerField()),
                ('max_price', models.SmallIntegerField()),
                ('pic', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='CommodityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=256)),
                ('big_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_user_ui.BigPic')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题名称')),
                ('title_show', models.BooleanField(default=True, verbose_name='是否显示标题')),
                ('data_type', models.SmallIntegerField(choices=[(1, '表格'), (2, '商品1/2图文'), (3, '轮播大图'), (4, '表格')], verbose_name='数据类型')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'default_related_name': 'default_related_name1',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='ShopName',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '店铺名称',
                'verbose_name_plural': '店铺名称',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('openid', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_user_ui.OrderInfo')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.ManyToManyField(to='wx_user_ui.ModuleType')),
            ],
            options={
                'verbose_name': '用户UI',
                'verbose_name_plural': '用户UI',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wx_user_ui.CommodityInfo'),
        ),
    ]
