# Generated by Django 2.1.7 on 2019-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_show', models.BooleanField(default=True)),
                ('data_type', models.SmallIntegerField(choices=[(1, '表格'), (2, '商品1/2图文'), (3, '轮播大图'), (4, '表格')])),
            ],
        ),
        migrations.CreateModel(
            name='UserUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.ManyToManyField(to='wx_user_ui.ModuleType')),
            ],
        ),
    ]
