# Generated by Django 2.1.7 on 2019-03-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0002_auto_20190303_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduletype',
            options={'verbose_name': '微读书1', 'verbose_name_plural': '商品类型'},
        ),
    ]
