# Generated by Django 2.1.7 on 2019-03-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0003_auto_20190303_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduletype',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterModelOptions(
            name='userui',
            options={'verbose_name': '用户UI', 'verbose_name_plural': '用户UI'},
        ),
    ]
