# Generated by Django 2.1.7 on 2019-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0004_auto_20190303_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
    ]
