# Generated by Django 2.1.7 on 2019-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0005_auto_20190303_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletype',
            name='data_type',
            field=models.SmallIntegerField(choices=[(1, '表格'), (2, '商品1/2图文'), (3, '轮播大图'), (4, '表格')], verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题名称'),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='title_show',
            field=models.BooleanField(default=True, verbose_name='是否显示标题'),
        ),
    ]
