# Generated by Django 2.1.7 on 2019-03-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0006_auto_20190303_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduletype',
            options={'default_related_name': 'default_related_name', 'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
    ]
