# Generated by Django 2.1.7 on 2019-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0007_auto_20190303_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigImage',
            fields=[
                ('image_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=100)),
                ('image_path', models.FilePathField()),
            ],
        ),
    ]
