# Generated by Django 2.1.7 on 2019-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0008_bigimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigimage',
            name='image_path',
            field=models.CharField(max_length=100),
        ),
    ]
