# Generated by Django 2.1.7 on 2019-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0009_auto_20190303_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigimage',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
