# Generated by Django 2.1.7 on 2019-03-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0010_auto_20190303_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopName',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '店铺名称',
                'verbose_name_plural': '店铺名称',
            },
        ),
        migrations.AlterModelOptions(
            name='bigimage',
            options={'ordering': ('image_id',), 'verbose_name': '大图', 'verbose_name_plural': '大图'},
        ),
    ]
