# Generated by Django 2.1.7 on 2019-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx_user_ui', '0011_auto_20190305_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_price', models.SmallIntegerField()),
                ('mix_price', models.SmallIntegerField()),
                ('pic', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
